name: "General issue"
description: Open a general issue for this repo and the SATRE team project board
body:
- type: markdown
  attributes:
    value: |
      This template will guide you through the steps necessary to open an issue for this repo!
- type: textarea
  id: summary
  attributes:
    label: Summary of issue
    description: Add a summary of your issue here. You can link it to another issue by using a `#` followed by the issue number.
  validations:
    required: true
- type: textarea
  id: actions
  attributes: 
    label: What needs to be done?
    description: Add a checklist of tasks that need to be done. We recommend creating this list using bulletpoints (indicated by * or -), followed by square brackets separated by a space [ ]. This will create a checkbox!
    placeholder: Please use bulletpoints (* or -) and filled checkboxes ([ ]) as necessary. To fill a checkbox put an x in the middle ([x])
  validations:
    required: true
- type: textarea
  id: help
  attributes:
    label: Who can help?
    description: Add here who can help - you can do this by typing `@` followed by their GitHub username. We recommend creating this list using bulletpoints (indicated by * or -)
    placeholder: Please use bulletpoints (* or -) to list who can help
- type: checkboxes
  id: checklist
  attributes:
    label: Issue checklist
    description: Please ensure you have done these tasks before progressing with this issue
    options:
      - label: I have assigned the appropriate work package label to this issue, and added any other relevant labels
      - label: I have added this to the `SATRE backlog (public)` project board
      - label: I have assigned this issue to at least one person on the SATRE team
  validations:
    required: true
        
    
